# Generated by Django 4.2.13 on 2024-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
